{
  lib,
  pkgs,
  config,
  inputs,
  ...
}: let
  cfg = config.mynix.stmp;
  customPackages = import ../packages {inherit pkgs lib;};
in
  with lib; {
    options.mynix = {
      stmp = {
        enable = mkEnableOption "stmp Subsonic terminal client";
      };
    };

    config = mkIf cfg.enable {
      home.packages = [customPackages.stmp];

      # Define the stmp password secret
      age.secrets.stmp-password = {
        file = ../../secrets/stmp-password.age;
        mode = "400";
      };

      # Generate stmp config at activation time using the decrypted secret
      home.activation.stmpConfig = lib.hm.dag.entryAfter ["writeBoundary" "agenix"] ''
        STMP_CONFIG_DIR="$HOME/.config/stmp"
        mkdir -p "$STMP_CONFIG_DIR"

        PASSWORD=$(cat ${config.age.secrets.stmp-password.path})

        cat > "$STMP_CONFIG_DIR/stmp.toml" << EOF
# STMP Configuration for Navidrome
# Auto-generated by home-manager - do not edit manually

[server]
host = "${inputs.private.services.navidrome}"
scrobble = true

[auth]
username = "jmo"
password = "$PASSWORD"
plaintext = true
EOF

        chmod 600 "$STMP_CONFIG_DIR/stmp.toml"
      '';
    };
  }
