#!/bin/bash

docker-shell() {
	# easily "docker exec" into a running Docker container
	# latest version: https://gist.github.com/ljm42/2b3bfd8ff886015bbce8

	CONTAINERS=`docker ps | awk 'NR==1 {offset=index($0,"NAMES")};NR>1{print substr($0,offset)}' | sort -f | tr "\n" " "`

	echo
	echo "Choose a Docker container:"
	i=1
	for container in $CONTAINERS
	do
	echo "$((i++)) : $container"
	done

	read MYCHOICE
	CHOSEN=`echo $CONTAINERS | cut -d' ' -f$MYCHOICE 2>/dev/null`

	if [ "$CHOSEN" = "" ]; then
	echo Invalid option
	exit
	fi

	# try running bash, if exit code 126 then try running sh
	for SHELL in bash sh
	do
	clear
	echo " "
	echo -e '\E[30;42m'"\033[5m    $CHOSEN - $SHELL   \033[0m"
	echo  " "
	tput sgr0
	docker exec -it $CHOSEN $SHELL
	if [ $? -ne 126 ]; then
		break
	fi
	done
}

bwcp() {
	# Copy password to clipboard and print username
	# Usage: bwcp <searchterm>
	local item
	item=$(bw get item "$1")
	echo "$item" | jq -r '.login.password' | wl-copy
	echo "$item" | jq -r '.login.username'
}

juggle() {
	# Worktree-safe juggle: prefers local binary for isolation
	if [[ -x "./juggle" ]]; then
		./juggle "$@"
	elif local root="$(git rev-parse --show-toplevel 2>/dev/null)" && [[ -x "$root/juggle" ]]; then
		"$root/juggle" "$@"
	else
		~/Development/juggler/juggle "$@"
	fi
}

alias j='juggle'
