# IMPORTANT: This is a placeholder template file.
# During NixOS installation, this file MUST be replaced with the actual
# hardware-configuration.nix generated by nixos-generate-config.
#
# Installation steps:
# 1. Boot from NixOS installer USB
# 2. Partition and mount your disk
# 3. Run: nixos-generate-config --root /mnt
# 4. Clone this repo to /mnt/etc/nixfiles
# 5. Copy the generated /mnt/etc/nixos/hardware-configuration.nix to this location:
#    cp /mnt/etc/nixos/hardware-configuration.nix /mnt/etc/nixfiles/defs/hosts/aperture/
# 6. Install: nixos-install --flake /mnt/etc/nixfiles#aperture
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # This is a placeholder. The actual hardware configuration will be
  # generated during installation and will include:
  # - Boot loader settings
  # - File system mounts
  # - Swap configuration
  # - Hardware modules (initrd kernelModules, etc.)

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Placeholder filesystem - REPLACE WITH ACTUAL GENERATED CONFIG
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # Surface Go 2 typically has Intel CPU
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
